"""Fix

Revision ID: ef6b8185b1b2
Revises: 2e0e797a89bf
Create Date: 2024-07-03 12:59:45.072451

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ef6b8185b1b2'
down_revision = '2e0e797a89bf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
